/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labdatos1;

import javax.swing.JOptionPane;

/**
 *
 * @author Jack Howard Ortega
 */
public class PAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form PAdministrador
     */
    public PAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        BRegistrar = new javax.swing.JButton();
        Baddsala = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btacceptar = new javax.swing.JButton();
        accepted = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("admin");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Administrador");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 9, -1, -1));

        BRegistrar.setText("Registrar Usuarios");
        BRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 32, -1, -1));

        Baddsala.setText("Modificar Salas");
        Baddsala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaddsalaActionPerformed(evt);
            }
        });
        getContentPane().add(Baddsala, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 75, 137, -1));

        jLabel1.setText("ingrese contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 9, -1, -1));

        btacceptar.setText("Ingresar");
        btacceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btacceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btacceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 75, 109, -1));

        accepted.setEditable(false);
        getContentPane().add(accepted, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 111, 109, -1));
        getContentPane().add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 32, 109, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labdatos1/1536318074_444085_1536318195_noticia_normal.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistrarActionPerformed
        String admi = "admin";
        String pwde = pwd.getText();
       
        if(pwde.equals(admi)){
            PRegistrarse abrir = new PRegistrarse();
        abrir.setVisible(true);
        this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "contraseña incorrecta ");
        }
        
        
        
    }//GEN-LAST:event_BRegistrarActionPerformed

    private void BaddsalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaddsalaActionPerformed
       String adpas = "admin";
       String pas = pwd.getText();
        if(pas.equals(adpas)){
        PCrearSalas abrir = new PCrearSalas();
        abrir.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_BaddsalaActionPerformed

    private void btacceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btacceptarActionPerformed
       String pas = pwd.getText();
       String adpas = "admin";
       if(pas.equals(adpas)){
           accepted.setText("Bienvenido");
           
       }else{
           JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
       }
       
    }//GEN-LAST:event_btacceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BRegistrar;
    private javax.swing.JButton Baddsala;
    private javax.swing.JTextField accepted;
    private javax.swing.JButton btacceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pwd;
    // End of variables declaration//GEN-END:variables
}
