/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labdatos1;

import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jack Howard Ortega
 */
public class PCrearSalas extends javax.swing.JFrame {
    
    File archivo;
    
    public PCrearSalas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabladeSalas = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        fc1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        numS = new javax.swing.JTextField();
        nomS = new javax.swing.JTextField();
        sf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ruta1 = new javax.swing.JTextField();
        Select = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        fotosal = new javax.swing.JLabel();
        cargarfsal = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        disp = new javax.swing.JTextField();
        jSpinField3 = new com.toedter.components.JSpinField();
        jSpinField4 = new com.toedter.components.JSpinField();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nombre Sala", "#computadores", "Software", "Disponibilidad", "diainicial", "diafinal", "horainicial", "horafinal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla1);

        TabladeSalas.getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("numeros de computadores");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(219, 91, 150, 16);

        jLabel2.setText(" agregar software");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(219, 147, 96, 16);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(375, 91, 0, 0);

        jLabel4.setText("nombre de la  sala");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 91, 103, 16);

        jLabel5.setText("horarios de prestamos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 147, 126, 16);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(49, 581, 73, 28);

        numS.setText(" ");
        getContentPane().add(numS);
        numS.setBounds(219, 113, 137, 28);

        nomS.setText(" ");
        getContentPane().add(nomS);
        nomS.setBounds(40, 113, 167, 28);

        sf.setText(" ");
        getContentPane().add(sf);
        sf.setBounds(219, 169, 215, 28);

        jLabel7.setText("archivo de salas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 28, 90, 16);

        ruta1.setText("  ");
        ruta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruta1ActionPerformed(evt);
            }
        });
        getContentPane().add(ruta1);
        ruta1.setBounds(40, 50, 174, 28);

        Select.setText("Seleccionar");
        Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectActionPerformed(evt);
            }
        });
        getContentPane().add(Select);
        Select.setBounds(226, 50, 93, 28);

        jButton3.setText("Mostrar Registro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(219, 581, 119, 28);

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(219, 547, 71, 28);

        jLabel6.setText("solo de 2PM-6PM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 262, 96, 16);

        jLabel8.setText("Hora de inico");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 288, 73, 16);

        jLabel9.setText("PM");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(84, 328, 17, 16);

        jLabel10.setText("Hora de finalizacion");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 368, 108, 16);

        jLabel11.setText("PM");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(84, 396, 17, 16);

        jButton5.setText("Set");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(107, 390, 46, 28);

        jButton6.setText("Set");
        getContentPane().add(jButton6);
        jButton6.setBounds(107, 322, 46, 28);

        fotosal.setText("FOTO DE SALA");
        getContentPane().add(fotosal);
        fotosal.setBounds(219, 280, 250, 204);

        cargarfsal.setText("Cargar foto");
        cargarfsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarfsalActionPerformed(evt);
            }
        });
        getContentPane().add(cargarfsal);
        cargarfsal.setBounds(219, 490, 250, 28);

        jLabel12.setText("disponibilidad(1.disponible,2.ocupado)");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(219, 203, 215, 16);

        disp.setText(" ");
        getContentPane().add(disp);
        disp.setBounds(219, 225, 35, 28);
        getContentPane().add(jSpinField3);
        jSpinField3.setBounds(40, 322, 38, 28);
        getContentPane().add(jSpinField4);
        jSpinField4.setBounds(40, 390, 38, 28);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(219, 615, 74, 28);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(40, 175, 119, 28);

        jLabel13.setText("inicio");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(165, 175, 29, 16);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(40, 209, 119, 28);

        jLabel14.setText("final");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(165, 209, 23, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String SltDir = "c:\\user";
        File f = new File(SltDir);
        String ruta = "c:\\user";
        String arch = "User.txt";
        File archivo = new File(ruta,arch);
        if(!f.exists()){
            f.mkdir();
            try {
                archivo.createNewFile();
            }catch(IOException ex){
                JOptionPane.showMessageDialog(rootPane, "Archivo no encontrado");
            }
        }
        try(FileWriter fw = new FileWriter(archivo.getAbsoluteFile(),true)){
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(nomS.getText()+","+numS.getText()+","+sf.getText()+","+disp.getText());
            bw.newLine();
            bw.flush();
            bw.close();
            fw.close();
        }catch (IOException ex) {
            Logger.getLogger(PCrearSalas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultTableModel model = (DefaultTableModel) Tabla1.getModel();
        
          String NomSala = nomS.getText();
          int numCompu= Integer.parseInt(numS.getText());
          String software=sf.getText(); 
          int disponibilidad = Integer.parseInt(disp.getText());
        
        model.addRow(new Object[]{NomSala,numCompu,software,disponibilidad});
        
        nomS.setText("");
        numS.setText("");
        sf.setText("");
        disp.setText("");
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
File sal;
    private void cargarfsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarfsalActionPerformed
         int res;
        cargarfotosala ventanas = new cargarfotosala();
        ventanas.setVisible(true);
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG y PNG","jpg" ,"png");
        ventanas.FC2.setFileFilter(filter);
        res= ventanas.FC2.showOpenDialog(null);
          
        if(JFileChooser.APPROVE_OPTION == res){
            sal = ventanas.FC2.getSelectedFile();
            try{
              ImageIcon icon = new ImageIcon(sal.toString());
              Icon icono = new ImageIcon(icon.getImage().getScaledInstance(fotosal.getWidth(),fotosal.getHeight(),Image.SCALE_DEFAULT));
              fotosal.setText(null);
              fotosal.setIcon(icono);
              ventanas.setVisible(false);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"jinkies!! error abriendo la imagen"+ ex);
            }
            
        }
    }//GEN-LAST:event_cargarfsalActionPerformed

    private void SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectActionPerformed
 FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos .txt", "txt");
        
        fc1.setFileFilter(filter);
        
        int op = fc1.showOpenDialog(this);
        
        if (op == JFileChooser.APPROVE_OPTION) {
            
            archivo = fc1.getSelectedFile();
            
            ruta1.setText(archivo.getAbsolutePath());
            
            DefaultTableModel model = (DefaultTableModel) Tabla1.getModel();
            try(Scanner s = new Scanner(archivo)){
                while(s.hasNextLine()){
                    String linea = s.nextLine();
                    String datos[] = linea.split(",");
                    
                    String nomS = datos[0];
                    Integer numS = Integer.parseInt(datos[1]);
                    String sf = datos[2];
                    Integer disp = Integer.parseInt(datos[3]);
                    
                    model.addRow(new Object[]{nomS,numS,sf,disp});
                }
            } catch (FileNotFoundException ex) {
                System.out.println("nada");
                JOptionPane.showMessageDialog(null, "No se encontro el archivo");
            }
            
            
        }        
    }//GEN-LAST:event_SelectActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        TabladeSalas.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ruta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruta1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) Tabla1.getModel();
        
        int fila = Tabla1.getSelectedRow();
        
        model.removeRow(fila);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) Tabla1.getModel();
        
        try(BufferedWriter bw = new BufferedWriter(new FileWriter(archivo))){
            int fila = model.getRowCount();
            for (int i = 0; i < fila; i++) {
                
                Object nomS = model.getValueAt(i, 0);
                Object numS = model.getValueAt(i, 1);
                Object sf = model.getValueAt(i, 2);
                Object disp = model.getValueAt(i, 3);
                
                bw.write(nomS+","+numS+","+sf+","+disp);
                bw.newLine();
                
            }
        } catch (IOException ex) {
            Logger.getLogger(PCrearSalas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PCrearSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PCrearSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PCrearSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PCrearSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PCrearSalas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Select;
    private javax.swing.JTable Tabla1;
    private javax.swing.JFrame TabladeSalas;
    private javax.swing.JButton cargarfsal;
    private javax.swing.JTextField disp;
    private javax.swing.JFileChooser fc1;
    private javax.swing.JLabel fotosal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.components.JSpinField jSpinField3;
    private com.toedter.components.JSpinField jSpinField4;
    private javax.swing.JTextField nomS;
    private javax.swing.JTextField numS;
    private javax.swing.JTextField ruta1;
    private javax.swing.JTextField sf;
    // End of variables declaration//GEN-END:variables
}
