/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labdatos1;

import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jack Howard Ortega
 */
public class PRegistrarse extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
 File archivo;
    /**
     * Creates new form PRegistrarse
     */
    public PRegistrarse() {
        initComponents();
        modelo.addColumn("nombre");
        modelo.addColumn("cedula");
        modelo.addColumn("correo");
        Tabla2.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc2 = new javax.swing.JFileChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomU = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CedU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CorreoU = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lblfoto = new javax.swing.JLabel();
        cargarfoto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ruta2 = new javax.swing.JTextField();
        Select2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registrar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 7, -1, -1));

        nomU.setText(" ");
        nomU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomUActionPerformed(evt);
            }
        });
        getContentPane().add(nomU, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 94, 195, -1));

        jLabel2.setText("Nombre de Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 75, 195, -1));

        jLabel3.setText("Cedula");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 123, -1, -1));

        CedU.setText(" ");
        getContentPane().add(CedU, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 146, 195, -1));

        jLabel4.setText("Correo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 175, -1, -1));

        CorreoU.setText(" ");
        getContentPane().add(CorreoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 198, 195, -1));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 499, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tipo de usuario", "Estudiante", "Profesor" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 444, 116, -1));

        jLabel5.setText("Foto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 227, -1, -1));

        lblfoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfoto.setText("foto ");
        lblfoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 195, 115));

        cargarfoto.setText("Cargar foto");
        cargarfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarfotoActionPerformed(evt);
            }
        });
        getContentPane().add(cargarfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 195, -1));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 499, -1, -1));
        getContentPane().add(ruta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 37, 104, -1));

        Select2.setText("Archivo");
        Select2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select2ActionPerformed(evt);
            }
        });
        getContentPane().add(Select2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 36, -1, -1));

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nombre", "cedula", "correo"
            }
        ));
        jScrollPane2.setViewportView(Tabla2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 44, -1, -1));

        modificar.setText("actualizar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 473, -1, -1));

        eliminar.setText("eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 473, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labdatos1/1536318074_444085_1536318195_noticia_normal.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 540));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 7, -1, -1));

        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 190, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 496, -1, 40));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 200, -1));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 190, -1));

        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) Tabla2.getModel();
        
        try(BufferedWriter bw = new BufferedWriter(new FileWriter(archivo))){
            int fila = model.getRowCount();
            for (int i = 0; i < fila; i++) {
                
                Object nom = model.getValueAt(i, 0);
                Object ced = model.getValueAt(i, 1);
                Object correo = model.getValueAt(i, 2);
               
                
                bw.write(nom+","+ced+","+correo);
                bw.newLine();
                
            }
        } catch (IOException ex) {
            Logger.getLogger(Clase.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
File fichero;

    private void cargarfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarfotoActionPerformed
            int resultado;
        cargarfoto ventana = new cargarfoto();
        ventana.setVisible(true);
        
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG","jpg" ,"png");
        ventana.FC.setFileFilter(filtro);
        resultado= ventana.FC.showOpenDialog(null);
          
        if(JFileChooser.APPROVE_OPTION == resultado){
            fichero = ventana.FC.getSelectedFile();
            try{
              ImageIcon icon = new ImageIcon(fichero.toString());
              Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblfoto.getWidth(),lblfoto.getHeight(),Image.SCALE_DEFAULT));
              lblfoto.setText(null);
              lblfoto.setIcon(icono);
              ventana.setVisible(false);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"jinkies!! error abriendo la imagen"+ ex);
            }
            
        }
        
        
    }//GEN-LAST:event_cargarfotoActionPerformed

    private void Select2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select2ActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos .txt", "txt");
        
        fc2.setFileFilter(filter);
        
        int op = fc2.showOpenDialog(this);
        
        if (op == JFileChooser.APPROVE_OPTION) {
            
            archivo = fc2.getSelectedFile();
            
            ruta2.setText(archivo.getAbsolutePath());
            
            DefaultTableModel model = (DefaultTableModel) Tabla2.getModel();
            try(Scanner s = new Scanner(archivo)){
                while(s.hasNextLine()){
                    String linea = s.nextLine();
                    String datos[] = linea.split(",");
                    
                    String nomS = datos[0];
                    Integer numS = Integer.parseInt(datos[1]);
                    String sf = datos[2];
                    Integer disp = Integer.parseInt(datos[3]);
                    
                    
                    model.addRow(new Object[]{nomS,numS,sf,disp});
                }
            } catch (FileNotFoundException ex) {
                System.out.println("nada");
                JOptionPane.showMessageDialog(null, "No se encontro el archivo");
            }
            
            
        } 
    }//GEN-LAST:event_Select2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String SltDir = "c:\\user";
        File f = new File(SltDir);
        String ruta = "c:\\user";
        String arch = "User.txt";
        File archivo = new File(ruta,arch);
        if(!f.exists()){
            f.mkdir();
            try {
                archivo.createNewFile();
            }catch(IOException ex){
                JOptionPane.showMessageDialog(rootPane, "Archivo no encontrado");
            }
        }
        
        String dato [] = new String[3];
        dato[0]= nomU.getText();
        dato[1]=CedU.getText();
        dato[2]=CorreoU.getText();
        modelo.addRow(dato);
        
        nomU.setText("");
        CedU.setText("");
        CorreoU.setText("");
        nomU.requestFocus();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void nomUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomUActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        int FilaSelec = Tabla2.getSelectedRow();
        if(FilaSelec>= 0){
            nomU.setText(Tabla2.getValueAt(FilaSelec,0).toString());
            CedU.setText(Tabla2.getValueAt(FilaSelec,1).toString());
            CorreoU.setText(Tabla2.getValueAt(FilaSelec,2).toString());
            modelo.removeRow(FilaSelec);
        }else{
            JOptionPane.showMessageDialog(this,"no ha seleccionado");
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
         int FilaSelec = Tabla2.getSelectedRow();
        if(FilaSelec>= 0){
            modelo.removeRow(FilaSelec);
        }else{
            JOptionPane.showMessageDialog(this,"no ha seleccionado");
        }
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRegistrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CedU;
    private javax.swing.JTextField CorreoU;
    private javax.swing.JButton Select2;
    private javax.swing.JTable Tabla2;
    private javax.swing.JButton cargarfoto;
    private javax.swing.JButton eliminar;
    private javax.swing.JFileChooser fc2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nomU;
    private javax.swing.JTextField ruta2;
    // End of variables declaration//GEN-END:variables
}
